name: Rust CI
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Run tests
      run: cargo test --verbose --all-features
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Run Clippy
      run: cargo clippy --verbose
    - name: Run rustfmt
      run: cargo fmt --all --check
